blank_issues_enabled: false
contact_links:
  - name: Website
    url: https://calloo.github.io/night-vision-ext/
    about: Website/docs
  - name: Twitter
    url: https://twitter.com/nvxbased
    about: Follow us on twitter
